version: '3.3'
services:
  node:
    image: node:latest
    working_dir: /app 
    volumes:
      - ./:/app
      - /app/node_modules

    command: 
      - npm install 
      - npm run dev 
   
  iginx1: 
    image: nginx:latest 
    ports: 
     - "5002:80" 
    working_dir: /app 
    volumes:
       - ./:/usr/share/nginx/html/ 
    depends_on:  
        - node
